scan_timeout = 60
add_newline = false
command_timeout = 3600

format = "$directory$git_branch[\\$](bright-black) "
right_format = "$nix_shell"

[nix_shell]
format = " [󱄅 $state]($style)"
style = "bright-black"

[directory]
format = "[$path]($style) "
truncate_to_repo = false
style = "blue"

[git_branch]
format = "[$branch]($style) "
style = "purple"
